DROP TABLE IF EXISTS listing CASCADE;

-- CREATE LISTINGS
CREATE TABLE listing (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  price VARCHAR(255) NOT NULL
);