DROP TABLE IF EXISTS bookings CASCADE;

-- CREATE BOOKINGS
CREATE TABLE bookings (
  id SERIAL PRIMARY KEY,
  listing_id INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  start_date TIMESTAMP,
  end_date TIMESTAMP 
);